In [89]:
import numpy as np
import scipy.linalg as la

In [119]:
arr = np.random.randn(3,3)
arr     

array([[-1.01307516,  0.63509241,  2.06755001],
       [ 1.68824494, -0.67657794, -0.22505165],
       [-0.72738808, -0.00658651, -0.22604821]])

1. Get eigenvalues and eigen vectors

In [10]:
eigvals, eigvecs = la.eig(arr)
print(eigvals)

[ 0.81903672+2.19335982j  0.81903672-2.19335982j -0.7822762 +0.j        ]


In [11]:
print(eigvecs)

[[ 0.65207011+0.j          0.65207011-0.j          0.4184182 +0.j        ]
 [ 0.17698397+0.55622206j  0.17698397-0.55622206j -0.36753157+0.j        ]
 [-0.24284181+0.41848073j -0.24284181-0.41848073j  0.83057014+0.j        ]]


2. digitize

we can get the indices of the bins to which the each value is belongs

In [4]:
a = np.array([1.2, 2.4, 3.6, 4.8]) 
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0]) 
  
# using np.digitize() method 
gfg = np.digitize(a, bins) 
  
print(gfg) 

[1 2 3 4]


3. repeat

In [4]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [5]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

4.squeeze

The squeeze() function is used to remove single-dimensional entries from the shape of an array.

axis	Selects a subset of the single-dimensional entries in the shape. If an axis is selected with shape entry greater than one, an error is raised.
squeezed [ndarray] The input array, but with all or a subset of the dimensions of length 1 removed. This is always a itself or a view into a.

Raises: ValueError - If axis is not None, and an axis being squeezed is not of length 1


In [7]:
a = np.array([[[0], [2], [4]]])

In [11]:
a.shape

(1, 3, 1)

In [8]:
np.squeeze(a, axis=0).shape

(3, 1)

In [14]:
np.squeeze(a, axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [16]:
np.squeeze(a, axis=2).shape

(1, 3)

5.linspace

In [18]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [21]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

6. clip()

In [25]:
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ] 
print ("Input array : ", in_array) 

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]


In [26]:
out_array = np.clip(in_array, a_min = 2, a_max = 6) 
print ("Output array : ", out_array) 

Output array :  [2 2 3 4 5 6 6 6]


In [27]:
in_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
print ("Input array : ", in_array) 
  
out_array = np.clip(in_array, a_min =[3, 4, 1, 1, 1, 4, 4, 4, 4, 4],a_max = 9) 
print ("Output array : ", out_array) 


Input array :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Output array :  [3 4 3 4 5 6 7 8 9 9]


7.extract()

Returns Rank 1 array of values  where condition is True.

In [30]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
condition = np.mod(arr, 3)==0
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [32]:
np.extract(condition, arr)

array([0, 3, 6, 9])

8.argpartition

Let us understand partition first

takes the kth item in sorted order, and puts it in the correct place if the array was sorted. All shorter elements are moved before the kth item, and all larger items are moved after the kth item, but not necessarily in sorted order.

In [38]:
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])
arr

array([ 90,  14,  24,  13,  13, 590,   0,  45,  16,  50])

In [37]:
arr.partition((4, 7))
arr

array([  0,  13,  13,  14,  16,  24,  45,  50, 590,  90])

14 (the 4th item) and 45 (the 7th item) are in the correct sorted positions. Think of them as walls. Everything less than 14 is to the left of the 14 wall. Everything between 14 and 45 is in between the two walls, and everything greater than 45 is to the right of the 45 wall. So the two walls create three partitions. Within the partitions, things are not sorted, they're just thrown in there and land where they will.

In [39]:
arr[np.argpartition(arr,(1,5))]

array([  0,  13,  14,  13,  16,  24,  45,  50,  90, 590])

In [40]:
arr[np.argpartition(arr, 3)]

array([ 13,   0,  13,  14,  16,  24,  45,  50, 590,  90])

9.setdiff1d()

Find the set difference of two arrays.

Return the unique values in ar1 that are not in ar2.

In [43]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])

In [44]:
np.setdiff1d(a, b)

array([1, 2])

10.itemsize

itemsize returns the size (in bytes) of each element of a NumPy array.

In [47]:
arr.itemsize

4

In [49]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


11. hstack

In [51]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [52]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

12.vstack

In [53]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [54]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

13. hsplit

hsplit is equivalent to split with axis=1, the array is always split along the second axis regardless of the array dimension.

In [56]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [57]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [58]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]), array([[ 3.],
        [ 7.],
        [11.],
        [15.]]), array([], shape=(4, 0), dtype=float64)]

14. vsplit

In [60]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [61]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

15. view vs shallow copy

Shallow copy: In case shallow copy if you change value in one variable it will reflect a change into other variable. 


Here are the main differences between views and copies:

Modifying the array

       Modifying a view modifies the base (original) array, whereas modifying a copy does not modify the base array.
       
Time taken

      Making a copy takes more time, often 1.5x-2x longer.
      
Base of the array

      A view has the same base as its base array. A copy does not.
      
Memory

      A view also shares memory with the base array, whereas a copy does not.
      

In [94]:
a = np.array([1,2,3,4])

In [98]:
b=a
c = a.view() 


In [99]:
print("a",a)
print("b",b)
print("c",c)
print(id(a)) 
print(id(b)) 
print(id(c))

a [1 2 3 4]
b [1 2 3 4]
c [1 2 3 4]
1801319926400
1801319926400
1801319824000


In [101]:
b[0]=353
print("a=",a)
print("b=",b)
print("c=",c)


a= [353   2   3   4]
b= [353   2   3   4]
c= [353   2   3   4]


In [102]:
c[0]=5
print("a=",a)
print("b=",b)
print("c=",c)

a= [5 2 3 4]
b= [5 2 3 4]
c= [5 2 3 4]


16. Depp Copy and 17. Copy

Deep copy is a process in which the copying process occurs recursively. It means first constructing a new collection object and then recursively populating it with copies of the child objects found in the original. In case of deep copy, a copy of object is copied in other object. It means that any changes made to a copy of object do not reflect in the original object. In python, this is implemented using “deepcopy()” function.

In [76]:
import copy 
  
# initializing list 1  
li1 = [1, 2, [3,5], 4] 
  
# using copy for shallow copy   
li2 = copy.copy(li1)  
  
# using deepcopy for deepcopy   
li3 = copy.deepcopy(li1)  

In [92]:
print("Original :",li1)
print("Copy :",li2)
print("Deep Copy :",li3)
print(id(li1))  
print(id(li2))
print(id(li3))

Original : [1, 2, [3, 5], 4]
Copy : [1, 2, [3, 5], 4]
Deep Copy : [1, 2, [5, 5], 4]
1801319760072
1801319759944
1801319728392


In [78]:
li3[2]=[5,5]

In [79]:
print("Original :",li1)
print("Copy :",li2)
print("Deep Copy :",li3)

Original : [1, 2, [3, 5], 4]
Copy : [1, 2, [3, 5], 4]
Deep Copy : [1, 2, [5, 5], 4]


18. Meshgrid

https://www.javatpoint.com/numpy-meshgrid

In [103]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)

In [104]:
x

array([0. , 0.5, 1. ])

In [105]:
y

array([0., 1.])

In [106]:
xv, yv = np.meshgrid(x, y)

In [107]:
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [108]:
yv

array([[0., 0., 0.],
       [1., 1., 1.]])

In [109]:
xv, yv = np.meshgrid(x, y, sparse=True)

In [110]:
xv

array([[0. , 0.5, 1. ]])

In [111]:
yv

array([[0.],
       [1.]])

19. Swapaxes

In [114]:
a = np.arange(8).reshape(2,2,2) 
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [116]:
print(np.swapaxes(a, 2, 0)) 

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


20. column_stacks()

In [118]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])